# Generated by Django 3.2.18 on 2023-04-14 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voetbalspeler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='naamVoetballer',
            new_name='Naam voetballer',
        ),
    ]
