# Generated by Django 3.2.18 on 2023-04-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voetbalspeler', '0004_rename_naamvoetballer_voetbalspeler_naamwim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='NaamWim',
            new_name='naamVoetballer',
        ),
    ]
