# Generated by Django 3.2.18 on 2023-04-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_voetbalspeler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspeler',
        ),
    ]
